package com.projectiq.mcp.recommendation.dto;

/**
 * Categories of recommendations generated by the Intelligent Recommendation Engine.
 * Each recommendation belongs to exactly one category.
 */
public enum RecommendationCategory {
    IMPLEMENTATION,
    ARCHITECTURE,
    TESTING,
    PERFORMANCE,
    DEPENDENCY,
    CONFIGURATION,
    REFACTORING,
    DOCUMENTATION,
    RISK_MITIGATION
}