package com.projectiq.mcp.recommendation.dto;

/**
 * Priority levels for recommendations generated by the Intelligent Recommendation Engine.
 * Recommendations are ordered by priority: Critical, High, Medium, Low.
 */
public enum RecommendationPriority {
    CRITICAL,
    HIGH,
    MEDIUM,
    LOW
}