package com.projectiq.mcp.knowledge.dto;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a unified deterministic knowledge report generated by the
 * Development Knowledge Engine. Contains all repository intelligence,
 * architectural insights, workflow information, development sessions,
 * recommendations, and evolution insights consolidated into a single report.
 *
 * <p>All fields are deterministic and based solely on indexed data.</p>
 */
public class KnowledgeReport {

    private String repositoryName;
    private String branch;
    private String query;
    private String knowledgeDomain;
    private long generatedAtMillis;
    private long generationDurationMillis;

    // Repository overview
    private String repositoryOverview;

    // Architecture summary
    private String architectureSummary;

    // Component relationships
    private List<String> componentRelationships = new ArrayList<>();

    // Active development sessions
    private List<String> activeSessions = new ArrayList<>();

    // Workflow summaries
    private List<String> workflowSummaries = new ArrayList<>();

    // Repository health
    private String repositoryHealth;

    // Risks
    private List<String> risks = new ArrayList<>();

    // Recommendations
    private List<String> recommendations = new ArrayList<>();

    // Evolution insights
    private List<String> evolutionInsights = new ArrayList<>();

    // Unified repository knowledge summary
    private String unifiedSummary;

    // Status
    private String status;
    private String errorMessage;

    // Report metadata
    private ReportMetadata metadata;

    public KnowledgeReport() {
        this.generatedAtMillis = System.currentTimeMillis();
        this.status = "SUCCESS";
    }

    // --- Nested Metadata class ---

    public static class ReportMetadata {
        private int totalSessions;
        private int activeSessionCount;
        private int completedSessionCount;
        private int totalWorkflowCount;
        private int totalRecommendations;
        private int totalRisks;
        private int totalComponentRelationships;
        private String knowledgeGraphSummary;

        public ReportMetadata() {
        }

        public int getTotalSessions() {
            return totalSessions;
        }

        public void setTotalSessions(int totalSessions) {
            this.totalSessions = totalSessions;
        }

        public int getActiveSessionCount() {
            return activeSessionCount;
        }

        public void setActiveSessionCount(int activeSessionCount) {
            this.activeSessionCount = activeSessionCount;
        }

        public int getCompletedSessionCount() {
            return completedSessionCount;
        }

        public void setCompletedSessionCount(int completedSessionCount) {
            this.completedSessionCount = completedSessionCount;
        }

        public int getTotalWorkflowCount() {
            return totalWorkflowCount;
        }

        public void setTotalWorkflowCount(int totalWorkflowCount) {
            this.totalWorkflowCount = totalWorkflowCount;
        }

        public int getTotalRecommendations() {
            return totalRecommendations;
        }

        public void setTotalRecommendations(int totalRecommendations) {
            this.totalRecommendations = totalRecommendations;
        }

        public int getTotalRisks() {
            return totalRisks;
        }

        public void setTotalRisks(int totalRisks) {
            this.totalRisks = totalRisks;
        }

        public int getTotalComponentRelationships() {
            return totalComponentRelationships;
        }

        public void setTotalComponentRelationships(int totalComponentRelationships) {
            this.totalComponentRelationships = totalComponentRelationships;
        }

        public String getKnowledgeGraphSummary() {
            return knowledgeGraphSummary;
        }

        public void setKnowledgeGraphSummary(String knowledgeGraphSummary) {
            this.knowledgeGraphSummary = knowledgeGraphSummary;
        }
    }

    // --- Getters and Setters ---

    public String getRepositoryName() {
        return repositoryName;
    }

    public void setRepositoryName(String repositoryName) {
        this.repositoryName = repositoryName;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    public String getKnowledgeDomain() {
        return knowledgeDomain;
    }

    public void setKnowledgeDomain(String knowledgeDomain) {
        this.knowledgeDomain = knowledgeDomain;
    }

    public long getGeneratedAtMillis() {
        return generatedAtMillis;
    }

    public void setGeneratedAtMillis(long generatedAtMillis) {
        this.generatedAtMillis = generatedAtMillis;
    }

    public long getGenerationDurationMillis() {
        return generationDurationMillis;
    }

    public void setGenerationDurationMillis(long generationDurationMillis) {
        this.generationDurationMillis = generationDurationMillis;
    }

    public String getRepositoryOverview() {
        return repositoryOverview;
    }

    public void setRepositoryOverview(String repositoryOverview) {
        this.repositoryOverview = repositoryOverview;
    }

    public String getArchitectureSummary() {
        return architectureSummary;
    }

    public void setArchitectureSummary(String architectureSummary) {
        this.architectureSummary = architectureSummary;
    }

    public List<String> getComponentRelationships() {
        return componentRelationships;
    }

    public void setComponentRelationships(List<String> componentRelationships) {
        this.componentRelationships = componentRelationships != null
                ? new ArrayList<>(componentRelationships)
                : new ArrayList<>();
    }

    public List<String> getActiveSessions() {
        return activeSessions;
    }

    public void setActiveSessions(List<String> activeSessions) {
        this.activeSessions = activeSessions != null
                ? new ArrayList<>(activeSessions)
                : new ArrayList<>();
    }

    public List<String> getWorkflowSummaries() {
        return workflowSummaries;
    }

    public void setWorkflowSummaries(List<String> workflowSummaries) {
        this.workflowSummaries = workflowSummaries != null
                ? new ArrayList<>(workflowSummaries)
                : new ArrayList<>();
    }

    public String getRepositoryHealth() {
        return repositoryHealth;
    }

    public void setRepositoryHealth(String repositoryHealth) {
        this.repositoryHealth = repositoryHealth;
    }

    public List<String> getRisks() {
        return risks;
    }

    public void setRisks(List<String> risks) {
        this.risks = risks != null ? new ArrayList<>(risks) : new ArrayList<>();
    }

    public List<String> getRecommendations() {
        return recommendations;
    }

    public void setRecommendations(List<String> recommendations) {
        this.recommendations = recommendations != null
                ? new ArrayList<>(recommendations)
                : new ArrayList<>();
    }

    public List<String> getEvolutionInsights() {
        return evolutionInsights;
    }

    public void setEvolutionInsights(List<String> evolutionInsights) {
        this.evolutionInsights = evolutionInsights != null
                ? new ArrayList<>(evolutionInsights)
                : new ArrayList<>();
    }

    public String getUnifiedSummary() {
        return unifiedSummary;
    }

    public void setUnifiedSummary(String unifiedSummary) {
        this.unifiedSummary = unifiedSummary;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public ReportMetadata getMetadata() {
        return metadata;
    }

    public void setMetadata(ReportMetadata metadata) {
        this.metadata = metadata;
    }
}