package com.projectiq.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.projectiq.mcp.orchestration.dto.StepDependency;
import com.projectiq.mcp.orchestration.dto.WorkflowDefinition;
import com.projectiq.mcp.orchestration.dto.WorkflowExecutionResponse;
import com.projectiq.mcp.orchestration.service.WorkflowExecutionService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * MCP Tool that executes multi-step developer workflows generated by
 * the orchestrate_workflow tool. This tool manages workflow execution state,
 * step dependencies, progress tracking, and recovery.
 *
 * <p>The tool accepts a workflow generated by orchestrate_workflow, executes
 * all steps sequentially with dependency resolution, and returns a detailed
 * execution status including progress tracking, timeline, and final report.</p>
 */
@Component
public class ExecuteWorkflowTool {

    private static final Logger logger = LoggerFactory.getLogger(ExecuteWorkflowTool.class);

    private final WorkflowExecutionService workflowExecutionService;
    private final ObjectMapper objectMapper;

    public ExecuteWorkflowTool(WorkflowExecutionService workflowExecutionService) {
        this.workflowExecutionService = workflowExecutionService;
        this.objectMapper = new ObjectMapper();
        this.objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Executes a multi-step developer workflow.
     * Accepts a workflow definition (generated by orchestrate_workflow),
     * executes all steps with dependency validation and progress tracking,
     * and returns a detailed execution report.
     *
     * @param workflowDefinitionJson JSON representation of the workflow definition to execute
     * @param dependenciesJson       Optional JSON array of step dependencies (can be null or empty)
     * @return A structured JSON response containing the complete execution status
     */
    @Tool(description = """
            Executes a multi-step developer workflow generated by orchestrate_workflow.
            
            Accepts a workflow definition (JSON), executes all workflow steps in order
            respecting step dependencies, and returns detailed execution results.
            
            Response includes:
            - Workflow identifier
            - Workflow status (Pending, Running, Completed, Skipped, Failed, Cancelled)
            - Executed steps with results
            - Skipped steps with reasons
            - Failed steps with error details
            - Progress summary (total, completed, skipped, failed, remaining steps)
            - Execution timeline with step timestamps and durations
            - Final execution report with summary
                        
            This tool performs deterministic workflow execution only:
            - No AI models or LLMs are used
            - No code generation is performed
            - No repository modification occurs
            - Execution is sequential and deterministic
            """)
    public String executeWorkflow(String workflowDefinitionJson, String dependenciesJson) {
        try {
            // Validate input
            if (workflowDefinitionJson == null || workflowDefinitionJson.trim().isEmpty()) {
                return createErrorResponse("INVALID_ARGUMENT",
                        "Workflow definition JSON is required");
            }

            logger.info("Executing workflow from definition JSON");

            // Parse the workflow definition
            WorkflowDefinition definition;
            try {
                definition = objectMapper.readValue(workflowDefinitionJson, WorkflowDefinition.class);
            } catch (JsonProcessingException e) {
                return createErrorResponse("INVALID_ARGUMENT",
                        "Invalid workflow definition JSON: " + e.getMessage());
            }

            // Parse optional dependencies
            List<StepDependency> dependencies = new ArrayList<>();
            if (dependenciesJson != null && !dependenciesJson.trim().isEmpty()) {
                try {
                    StepDependency[] depArray = objectMapper.readValue(dependenciesJson, StepDependency[].class);
                    if (depArray != null) {
                        for (StepDependency dep : depArray) {
                            dependencies.add(dep);
                        }
                    }
                } catch (JsonProcessingException e) {
                    return createErrorResponse("INVALID_ARGUMENT",
                            "Invalid dependencies JSON: " + e.getMessage());
                }
            }

            // Execute the workflow
            WorkflowExecutionResponse response = workflowExecutionService.execute(definition, dependencies);

            return serializeResponse(response);

        } catch (IllegalArgumentException e) {
            return createErrorResponse("INVALID_ARGUMENT", e.getMessage());
        } catch (Exception e) {
            logger.error("Unexpected error executing workflow: {}", e.getMessage(), e);
            return createErrorResponse("INTERNAL_ERROR", "Internal error: " + e.getMessage());
        }
    }

    /**
     * Convenience method to execute a workflow without dependencies.
     *
     * @param workflowDefinitionJson JSON representation of the workflow definition to execute
     * @return A structured JSON response containing the complete execution status
     */
    @Tool(description = """
            Executes a multi-step developer workflow without step dependencies.
            A simpler version of execute_workflow for workflows with no dependency requirements.
            """)
    public String executeWorkflowSimple(String workflowDefinitionJson) {
        return executeWorkflow(workflowDefinitionJson, null);
    }

    private String serializeResponse(WorkflowExecutionResponse response) {
        try {
            return objectMapper.writeValueAsString(response);
        } catch (JsonProcessingException e) {
            return createErrorResponse("SERIALIZATION_ERROR",
                    "Failed to serialize execution result: " + e.getMessage());
        }
    }

    private String createErrorResponse(String errorType, String message) {
        try {
            return objectMapper.writeValueAsString(
                    new ExecuteWorkflowError(errorType, message)
            );
        } catch (JsonProcessingException e) {
            return "{\"errorType\":\"" + escapeJson(errorType)
                    + "\",\"message\":\"" + escapeJson(message) + "\"}";
        }
    }

    private String escapeJson(String value) {
        if (value == null) {
            return "";
        }
        return value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }

    /**
     * Simple error DTO for JSON error responses.
     */
    private static class ExecuteWorkflowError {
        public String errorType;
        public String message;

        public ExecuteWorkflowError(String errorType, String message) {
            this.errorType = errorType;
            this.message = message;
        }

        public String getErrorType() {
            return errorType;
        }

        public String getMessage() {
            return message;
        }
    }
}